#pragma once
// Compatibility umbrella. Core headers also compile independently; SDL is optional.
#include "bvh.h"
#include "camera.h"
#include "color.h"
#include "constants.h"
#include "cube.h"
#include "hittable_list.h"
#include "interval.h"
#include "light.h"
#include "material.h"
#include "quad.h"
#include "ray.h"
#include "sampler.h"
#include "sphere.h"
#include "vec3.h"
